# Generated by Django 4.1.5 on 2023-05-16 10:54

from django.db import migrations, models
import helpdesk.models


class Migration(migrations.Migration):
    dependencies = [
        ("helpdesk", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="demand",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to=helpdesk.models.Demand.file_upload
            ),
        ),
    ]
