# Generated by Django 4.0.6 on 2022-09-27 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0003_alter_demand_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demand',
            name='status',
            field=models.ForeignKey(default='Aguardando Atendimento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpdesk.status'),
        ),
    ]
