# Generated by Django 4.1.5 on 2023-05-16 11:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("helpdesk", "0003_demand_file_three_demand_file_two"),
    ]

    operations = [
        migrations.RenameField(
            model_name="demand",
            old_name="file",
            new_name="file_one",
        ),
    ]
