# Generated by Django 4.0.6 on 2022-11-29 11:06

from django.db import migrations, models
import helpdesk.models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_alter_demand_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='demand',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=helpdesk.models.Demand.image_upload),
        ),
        migrations.AlterField(
            model_name='demand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
