# Generated by Django 4.1.1 on 2022-12-04 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("helpdesk", "0006_alter_category_updated_at_alter_demand_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Historic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("historic", models.CharField(max_length=200, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "demand_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="helpdesk.demand",
                    ),
                ),
            ],
            options={
                "db_table": "helpdesk_historic",
                "managed": True,
            },
        ),
    ]
