# Generated by Django 4.0.6 on 2022-12-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_historic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='historic',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
