# Generated by Django 4.0.6 on 2022-12-14 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0006_alter_profile_user'),
        ('helpdesk', '0008_alter_historic_historic'),
    ]

    operations = [
        migrations.AddField(
            model_name='demand',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ti.department'),
        ),
    ]
