# Generated by Django 4.1.5 on 2023-03-09 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ti', '0006_alter_profile_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CpuDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_cpu_description',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CpuGeneration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.IntegerField(null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_cpu_generation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CpuManufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_cpu_manufacturer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CpuModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_cpu_model',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HardDiskSize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField(null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_hard_disk_size',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpu_description', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.cpudescription')),
                ('cpu_generation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.cpugeneration')),
                ('cpu_manufacturer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.cpumanufacturer')),
                ('cpu_model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.cpumodel')),
                ('hard_disk_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.harddisksize')),
            ],
            options={
                'db_table': 'inventory_hardware',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_invoice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MemorySize',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('size', models.IntegerField(null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_memory_size',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OperationalSystem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=35, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_operational_system',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
                ('description', models.CharField(max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_ranking',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StatusDescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'inventory_status_description',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StatusSituation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'inventory_status_situation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SystemArchitecture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('architecture', models.CharField(max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_system_architecture',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorkstationManufacturer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_workstation_manufacturer',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorkstationModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=55, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_workstation_model',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WorkstationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_workstation_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.statusdescription')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.statussituation')),
            ],
            options={
                'db_table': 'inventory_status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('architecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.systemarchitecture')),
                ('operating_system', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.operationalsystem')),
            ],
            options={
                'db_table': 'inventory_software',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inventory', models.IntegerField(null=True, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('workstation_serial', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ti.department')),
                ('hardware', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.hardware')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.invoice')),
                ('ranking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ranking')),
                ('software', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.software')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.status')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inventory_iventory',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='hardware',
            name='memory_size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.memorysize'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='workstation_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.workstationmanufacturer'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='workstation_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.workstationmodel'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='workstation_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.workstationtype'),
        ),
        migrations.AddConstraint(
            model_name='software',
            constraint=models.UniqueConstraint(fields=('operating_system', 'architecture'), name='unique_software_group'),
        ),
        migrations.AddConstraint(
            model_name='hardware',
            constraint=models.UniqueConstraint(fields=('workstation_type', 'workstation_manufacturer', 'cpu_manufacturer', 'cpu_model', 'cpu_generation', 'hard_disk_size', 'memory_size', 'workstation_model'), name='unique_hardware_group'),
        ),
    ]
