# Generated by Django 3.2.18 on 2023-03-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
