# Generated by Django 4.1.5 on 2023-03-21 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalSystemVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_operational_system_version',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OperationalSystemYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventory_operational_system_year',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hostname', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('IP', models.CharField(blank=True, max_length=15, null=True)),
                ('serviceRun', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.CharField(blank=True, max_length=120, null=True)),
                ('detail', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('software', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.software')),
            ],
            options={
                'db_table': 'inventory_server',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServerStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'inventory_status_server',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='description',
        ),
        migrations.AddField(
            model_name='inventory',
            name='detail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='operationalsystem',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='systemarchitecture',
            name='architecture',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='StatusDescription',
        ),
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.serverstatus'),
        ),
        migrations.AddField(
            model_name='software',
            name='operating_system_version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.operationalsystemversion'),
        ),
        migrations.AddField(
            model_name='software',
            name='operating_system_year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.operationalsystemyear'),
        ),
    ]
