# Generated by Django 4.1.5 on 2023-03-21 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_operationalsystemversion_operationalsystemyear_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='serverstatus',
            table='inventory_server_status',
        ),
    ]
