# Generated by Django 3.2.18 on 2023-03-09 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='description',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.statusdescription'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.statussituation'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
