# Generated by Django 3.2.18 on 2023-03-06 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_ranking_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpugeneration',
            old_name='generation',
            new_name='name',
        ),
    ]
