# Generated by Django 4.1.5 on 2023-04-05 11:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_remove_software_unique_software_group_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="IP",
            new_name="ip",
        ),
    ]
