# Generated by Django 3.2.18 on 2023-03-07 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_generation_cpugeneration_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoice',
            new_name='number',
        ),
    ]
