# Generated by Django 4.1.5 on 2023-03-21 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_serverstatus_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='software',
            name='operating_system_year',
        ),
        migrations.DeleteModel(
            name='OperationalSystemYear',
        ),
    ]
