# Generated by Django 4.1.5 on 2023-04-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0003_rename_ip_server_ip"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="link",
            new_name="url_external",
        ),
        migrations.AddField(
            model_name="server",
            name="url_internal",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
