# Generated by Django 3.2.18 on 2023-03-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_rename_invoice_invoice_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='operationalsystem',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='systemarchitecture',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='inventory',
            table='inventory_iventory',
        ),
        migrations.AlterModelTable(
            name='invoice',
            table='inventory_invoice',
        ),
        migrations.AlterModelTable(
            name='operationalsystem',
            table='inventory_operational_system',
        ),
        migrations.AlterModelTable(
            name='software',
            table='inventory_software',
        ),
        migrations.AlterModelTable(
            name='systemarchitecture',
            table='inventory_system_architecture',
        ),
    ]
