# Generated by Django 4.1.5 on 2023-03-21 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_remove_software_operating_system_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='software',
            name='architecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.systemarchitecture'),
        ),
    ]
