# Generated by Django 4.1.5 on 2023-03-28 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_software_architecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='serviceRun',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
