# Generated by Django 3.2.18 on 2023-03-07 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20230307_1119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cpudescription',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cpugeneration',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cpumanufacturer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='cpumodel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='harddisksize',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='memorysize',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ranking',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='workstationmanufacturer',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='workstationmodel',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='workstationtype',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='ranking',
        ),
        migrations.AddField(
            model_name='inventory',
            name='ranking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ranking'),
        ),
        migrations.AlterModelTable(
            name='cpudescription',
            table='inventory_cpu_description',
        ),
        migrations.AlterModelTable(
            name='cpugeneration',
            table='inventory_cpu_generation',
        ),
        migrations.AlterModelTable(
            name='cpumanufacturer',
            table='inventory_cpu_manufacturer',
        ),
        migrations.AlterModelTable(
            name='cpumodel',
            table='inventory_cpu_model',
        ),
        migrations.AlterModelTable(
            name='harddisksize',
            table='inventory_hard_disk_size',
        ),
        migrations.AlterModelTable(
            name='memorysize',
            table='inventory_memory_size',
        ),
        migrations.AlterModelTable(
            name='ranking',
            table='inventory_ranking',
        ),
        migrations.AlterModelTable(
            name='workstationmanufacturer',
            table='inventory_workstation_manufacturer',
        ),
        migrations.AlterModelTable(
            name='workstationmodel',
            table='inventory_workstation_model',
        ),
        migrations.AlterModelTable(
            name='workstationtype',
            table='inventory_workstation_type',
        ),
    ]
