# Generated by Django 3.2.18 on 2023-03-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20230307_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpudescription',
            name='name',
            field=models.CharField(max_length=80, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cpugeneration',
            name='name',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cpumanufacturer',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cpumodel',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='harddisksize',
            name='size',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='workstation_serial',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='hostname',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='inventory',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='memorysize',
            name='size',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operationalsystem',
            name='name',
            field=models.CharField(max_length=35, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='ranking',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='systemarchitecture',
            name='architecture',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workstationmanufacturer',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workstationmodel',
            name='name',
            field=models.CharField(max_length=55, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='workstationtype',
            name='name',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
