# Generated by Django 4.1.5 on 2023-05-17 14:48

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_alter_switch_password_alter_switch_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="switch",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=inventory.models.Switch.image_upload
            ),
        ),
    ]
