# Generated by Django 4.1.5 on 2023-05-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_switch_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="switch",
            name="inventory",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
