# Generated by Django 3.2.18 on 2023-03-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20230307_1147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hardware',
            options={'managed': True},
        ),
        migrations.RemoveField(
            model_name='hardware',
            name='workstation_serial',
        ),
        migrations.AddField(
            model_name='inventory',
            name='workstation_serial',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='hardware',
            table='inventory_hardware',
        ),
    ]
