# Generated by Django 3.2.18 on 2023-03-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20230307_1432'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='hardware',
            constraint=models.UniqueConstraint(fields=('workstation_type', 'workstation_manufacturer', 'cpu_manufacturer', 'cpu_model', 'cpu_generation', 'hard_disk_size', 'memory_size', 'workstation_model'), name='unique_hardware_group'),
        ),
        migrations.AddConstraint(
            model_name='software',
            constraint=models.UniqueConstraint(fields=('operating_system', 'architecture'), name='unique_software_group'),
        ),
    ]
