# Generated by Django 3.2.18 on 2023-03-07 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20230307_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.invoice'),
        ),
    ]
