# Generated by Django 3.2.18 on 2023-03-08 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_alter_inventory_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
