# Generated by Django 3.2.18 on 2023-03-09 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ti', '0006_alter_profile_user'),
        ('inventory', '0011_inventory_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'inventory_status_description',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StatusSituation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True, unique=True)),
            ],
            options={
                'db_table': 'inventory_status_situation',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='hardware',
            name='cpu_generation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.cpugeneration'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='workstation_manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.workstationmanufacturer'),
        ),
        migrations.AlterField(
            model_name='hardware',
            name='workstation_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.workstationmodel'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ti.department'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='hostname',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='ranking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.ranking'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='workstation_serial',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.statusdescription')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.statussituation')),
            ],
            options={
                'db_table': 'inventory_status',
                'managed': True,
            },
        ),
        migrations.AlterField(
            model_name='inventory',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.status'),
        ),
    ]
