# Generated by Django 4.0.6 on 2022-11-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restrictedarea',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='restrictedarea',
            table='ti_restricted_area',
        ),
    ]
